#!/bin/bash
#
#See skript on abiks ekskursiooni korraldamisel
#
read -p "Kui palju on reiskaid ?: " reisjad
read -p "Kui palju on bussis kohti ?: " bussis
xb=` expr $reisjad \/ $bussis `
xp=` expr $xb \+1 `
if (($reisjad % $bussis == 0))
then
    echo "Vaja on tellida $xb bussi"
else
    echo "Vaja on tellida $xp bussi"
fi
#
#Skripti lõpp
